[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "cold_coral_segmentation"
description = "Cold corals segmentation model"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "Apache 2.0" }
classifiers = [
    "Intended Audience :: Information Technology",
    "Intended Audience :: AI/ML/DL Researchers",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
]
dynamic = ["version", "dependencies"]

# Add author and author email here
authors = [
  {name= "Alberto Gaya Vilar", email= "alberto.gaya@ieo.csic.es"}
  {name= "Fahimeh Alibabaei", email= "khadijeh.alibabaei@kit.edu"},
  {name= "Lisana Berberi", email= "lisana.berberi@kit.edu"},
]

[project.urls]
"Homepage" = "https://github.com/ai4os-hub/cold-coral-segmentation/"
"Bug Tracker" = "https://github.com/ai4os-hub/cold-coral-segmentation/issues"

[tool.pytest.ini_options]
pythonpath = ["."]
env = ["DATA_PATH=tests/data", "MODELS_PATH=tests/models"]
addopts = "--import-mode=importlib"

[tool.setuptools]
packages = ["yolov8_api", "cold_coral_segmentation.api"]

[tool.setuptools.package-dir]
"cold_coral_segmentation.api" = "api"
"yolov8_api" = "yolov8_api"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
version = { file = "VERSION" }

[project.entry-points."deepaas.v2.model"]
cold_coral_segmentation = "cold_coral_segmentation.api"